import type { RecentCheck, WatchlistItem } from '@/lib/user-session';
import { SITE_CONFIG } from '@nexabit/shared';

function escapeCsv(value: string): string {
  if (/[",\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

export function exportWatchlistCsv(items: WatchlistItem[]) {
  const header = ['type', 'value', 'label', 'status', 'detail', 'last_checked'];
  const rows = items.map((i) =>
    [
      i.type,
      i.value,
      i.label,
      i.lastStatus ?? '',
      i.lastDetail ?? '',
      i.lastChecked ? new Date(i.lastChecked).toISOString() : '',
    ]
      .map(escapeCsv)
      .join(','),
  );
  downloadFile([header.join(','), ...rows].join('\n'), 'nexabit-watchlist.csv', 'text/csv');
}

export function exportRecentChecksCsv(checks: RecentCheck[]) {
  const header = ['tool', 'input', 'timestamp', 'href'];
  const rows = checks.map((c) =>
    [c.toolName, c.input, new Date(c.timestamp).toISOString(), c.href]
      .map(escapeCsv)
      .join(','),
  );
  downloadFile([header.join(','), ...rows].join('\n'), 'nexabit-recent-checks.csv', 'text/csv');
}

export function exportAuditReportHtml(options: {
  teamName: string;
  watchlist: WatchlistItem[];
  recentChecks: RecentCheck[];
  alerts: WatchlistItem[];
}) {
  const { teamName, watchlist, recentChecks, alerts } = options;
  const generated = new Date().toLocaleString();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${SITE_CONFIG.name} — Audit Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; color: #111; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    .meta { color: #555; font-size: 0.875rem; margin-bottom: 1.5rem; }
    h2 { font-size: 1.1rem; margin-top: 1.5rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; margin-top: 0.5rem; }
    th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
    th { background: #f5f5f5; }
    .alert { color: #b45309; }
    footer { margin-top: 2rem; font-size: 0.75rem; color: #666; }
  </style>
</head>
<body>
  <h1>Infrastructure Audit Report</h1>
  <p class="meta">${teamName} · Generated ${generated} · ${SITE_CONFIG.name}</p>

  <h2>Summary</h2>
  <ul>
    <li>Watchlist items: ${watchlist.length}</li>
    <li>Active alerts: ${alerts.length}</li>
    <li>Recent checks (session): ${recentChecks.length}</li>
  </ul>

  ${
    alerts.length
      ? `<h2>Alerts</h2><table><tr><th>Target</th><th>Status</th><th>Detail</th></tr>${alerts
          .map(
            (a) =>
              `<tr class="alert"><td>${a.value}</td><td>${a.lastStatus}</td><td>${a.lastDetail ?? ''}</td></tr>`,
          )
          .join('')}</table>`
      : ''
  }

  <h2>Watchlist</h2>
  <table>
    <tr><th>Type</th><th>Value</th><th>Status</th><th>Detail</th></tr>
    ${watchlist
      .map(
        (w) =>
          `<tr><td>${w.type}</td><td>${w.value}</td><td>${w.lastStatus ?? '—'}</td><td>${w.lastDetail ?? '—'}</td></tr>`,
      )
      .join('')}
  </table>

  <h2>Recent checks</h2>
  <table>
    <tr><th>Tool</th><th>Input</th><th>When</th></tr>
    ${recentChecks
      .slice(0, 20)
      .map(
        (c) =>
          `<tr><td>${c.toolName}</td><td>${c.input}</td><td>${new Date(c.timestamp).toLocaleString()}</td></tr>`,
      )
      .join('')}
  </table>

  <footer>
    Report generated by ${SITE_CONFIG.name} · ${SITE_CONFIG.company} ·
    <a href="${SITE_CONFIG.companyUrl}">${SITE_CONFIG.companyUrl}</a>
  </footer>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank', 'noopener,noreferrer');
  if (win) {
    win.onload = () => {
      win.print();
    };
  }
  URL.revokeObjectURL(url);
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
